### ISSUE TITLE
Week 11 Karthik Review Ticket Crossover

### ISSUE THREAD

**Issue by kar722** [Athena9355/Fire-Alarm#91]
TOTAL: 9.5/10

### Self-Score
Self-Score: 9.5/10

Part 1

- [x] PBL theme consistent through project and described in Github Pages: https://github.com/Athena9355/Fire-Alarm/blob/main/templates/pagelayout/index.html

- [x] Sassy / Bootstrap: https://github.com/Athena9355/Fire-Alarm/blob/main/templates/searchmeals/searchstyle.scss

- [x] Blueprint illustration/demonstration: https://github.com/Athena9355/Fire-Alarm/blob/main/templates/aboutus.py

- [x] CRUD Async Operation - runtime and understanding of JavaScript and Fetch: https://github.com/Athena9355/Fire-Alarm/tree/main/crud

- [ ] Individual PBL MVC feature/commits showing algorithms written in JS/Python: https://github.com/Athena9355/Fire-Alarm/blob/main/templates/darkmode.html

Runtime Features shown in 1 min video: https://youtu.be/NmKQVMv9rGY

- [x] Highlight of best features

- [x] CRUD/Search on project database tables, easy to identify from UI

- [x] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)

- [x] Google Search or Google translate implemented 

- [x] Scrum Board - Overview of completed tasks and Github tangibles

Part 2

- [x] Wiki/Jekyll page with design ideas and usage: https://athena9355.github.io/Fire-Alarm/

- [x] Create Performance Task PBL feature: https://github.com/Athena9355/Fire-Alarm/tree/main/templates/searchmeals

- [x] Final committed program code showing algorithms written in JS/Python: https://github.com/Athena9355/Fire-Alarm/commits?author=kar722

- [x] Written responses to all the prompts in the performance task: https://github.com/Athena9355/Fire-Alarm/wiki/Siya-Karthik-Create-Task-Questions

- [x] 1 min video that meets CB create task requirements: https://youtu.be/FYPpfhwftBc

**Comment by GavinYWu** [comment]
### Cross-over Score
Crossover Score: 9.5/10

#### Part 1
- [x] PBL theme consistent through project and described in Github Pages: .5/.5
- [x] Sassy / Bootstrap: .5/.5
- [x] Blueprint illustration/demonstration: .5/.5
- [x] CRUD Async Operation - runtime and understanding of JavaScript and Fetch: .5/.5
- [ ] Individual PBL MVC feature/commits showing algorithms written in JS/Python: 0/.5
Runtime Features shown in 1 min video:
- [x] Highlight of best features: .5/.5
- [x] CRUD/Search on project database tables, easy to identify from UI: .5/.5
- [x] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions): .5/.5
- [x] Google Search or Google translate implemented: .5/.5
- [x] Scrum Board - Overview of completed tasks and Github tangibles: .5/.5

#### Part 2
- [x] Wiki/Jekyll page with design ideas and usage: 1/1
- [x] Create Performance Task PBL feature: 1/1
- [x] Final committed program code showing algorithms written in JS/Python: 1/1
- [x] Written responses to all the prompts in the performance task: 1/1
- [x] 1 min video that meets CB create task requirements: 1/1
